# Generated by Django 4.1.5 on 2023-01-17 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_card', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('date_birth', models.DateField()),
                ('blood_type', models.CharField(max_length=4)),
                ('phone_number', models.CharField(max_length=16)),
                ('allergies', models.CharField(default='Ninguna', max_length=80)),
                ('id_history', models.CharField(max_length=15)),
                ('medical_family_history', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=30)),
                ('type_surgery', models.CharField(max_length=40)),
                ('reason_surgery', models.CharField(max_length=200)),
                ('surgery_urgency', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('is_derived', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
